const actions = {
  LOGOUT: 'LOGOUT',
  SMS_ERROR: 'SMS_ERROR',
  FETCH_USER: 'FETCH_USER',
  SMS_REQUEST: 'SMS_REQUEST',
  SMS_SUCCESS: 'SMS_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  FETCH_USER_ERROR: 'FETCH_USER_ERROR',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  CHECK_AUTHORIZATION: 'CHECK_AUTHORIZATION',
  CHANGE_PHONE_NUMBER: 'CHANGE_PHONE_NUMBER',
  SIGN_UP_REQUEST_ERROR: 'SIGN_UP_REQUEST_ERROR',
  SIGN_UP_REQUEST_SUCCESS: 'SIGN_UP_REQUEST_SUCCESS',
  CHECK_VERIFICATION_CODE: 'CHECK_VERIFICATION_CODE',
  GET_TOKEN_PUSH_NOTIFICATION: 'GET_TOKEN_PUSH_NOTIFICATION',
  CHECK_VERIFICATION_CODE_ERROR: 'CHECK_VERIFICATION_CODE_ERROR', 
  CHECK_VERIFICATION_CODE_SUCCESS: 'CHECK_VERIFICATION_CODE_SUCCESS',
  GET_TOKEN_PUSH_NOTIFICATION_ERROR: 'GET_TOKEN_PUSH_NOTIFICATION_ERROR',
  GET_TOKEN_PUSH_NOTIFICATION_SUCCESS: 'GET_TOKEN_PUSH_NOTIFICATION_SUCCESS',
  /// HANDLES ///
  login: (identifier, password, navigation) => ({ type: actions.LOGIN_REQUEST, payload: {identifier, password}, navigation }),
  logout: () => ({ type: actions.LOGOUT }),
  signUp: (payload) => ({ type: actions.SIGN_UP_REQUEST, payload }),
  authSMS: (payload, navigation) => ({ type: actions.SMS_REQUEST, payload, navigation }),
  getToken: () => ({ type: actions.GET_TOKEN_PUSH_NOTIFICATION }),
  fetchUser: (token) => ({ type: actions.FETCH_USER, token }),
  checkSession: () => ({ type: actions.CHECK_AUTHORIZATION }),
  changePhoneNumber: (prefix, phoneNumber) => ({ type: actions.CHANGE_PHONE_NUMBER, payload: { prefix, phoneNumber } }),
  checkAuthorization: (payload, navigation) => ({ type: actions.CHECK_VERIFICATION_CODE, payload, navigation }),
}

export default actions